// @ts-check
"use strict"

export var SERVICE_MESSAGE_EVENT = 'SERVICE_MESSAGE_EVENT';
export var FILE_PUT_EVENT = 'FILE_PUT_EVENT';
export var FILE_GET_EVENT = 'FILE_GET_EVENT';

export var FILETYPE_FOLDER = 0x4000;
export var FILETYPE_FILE = 0x8000;


export var NOOP = () => {};

export var BINARYSTATE_IDLE = 0;
export var BINARYSTATE_PUT_INITIAL_RESPONSE = 11;
export var BINARYSTATE_PUT_FINAL_RESPONSE = 12;
export var BINARYSTATE_GET_INITIAL_RESPONSE = 21;
export var BINARYSTATE_GET_DATA_TRANSFER = 22;
export var BINARYSTATE_GET_FINAL_RESPONSE = 23;
export var BINARYSTATE_GET_VERSION = 31;


